import type { Metadata, Viewport } from "next";
import "./globals.css";
import { ReactQueryClientProvider } from "@/app/_components/ReactQueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#0D9488"
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className="antialiased">
            {children}
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
